"""initial prospect schema

Revision ID: 92bd88dbcb33
Revises:
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '92bd88dbcb33'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('headquarters', sa.String(length=500), nullable=True),
    sa.Column('local_address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('distance_miles', sa.Float(), nullable=True),
    sa.Column('geographic_tier', sa.String(length=40), nullable=False),
    sa.Column('warehouse_evidence_status', sa.String(length=40), nullable=False),
    sa.Column('distribution_evidence_status', sa.String(length=40), nullable=False),
    sa.Column('research_status', sa.String(length=40), nullable=False),
    sa.Column('pipeline_stage', sa.String(length=40), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_domain'), 'accounts', ['domain'], unique=False)
    op.create_index(op.f('ix_accounts_normalized_name'), 'accounts', ['normalized_name'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflow_name', sa.String(length=100), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('usage_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approvals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer', sa.String(length=255), nullable=False),
    sa.Column('decision', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'decision', name='uq_account_decision')
    )
    op.create_index(op.f('ix_approvals_account_id'), 'approvals', ['account_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_account_id'), 'audit_events', ['account_id'], unique=False)
    op.create_table('fit_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=1), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('component_scores', sa.JSON(), nullable=False),
    sa.Column('penalties', sa.JSON(), nullable=False),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('uncertainties', sa.JSON(), nullable=False),
    sa.Column('disqualifying_questions', sa.JSON(), nullable=False),
    sa.Column('sales_cycle_category', sa.String(length=40), nullable=False),
    sa.Column('implementation_complexity', sa.String(length=40), nullable=False),
    sa.Column('support_burden', sa.String(length=40), nullable=False),
    sa.Column('recommended_next_action', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fit_scores_account_id'), 'fit_scores', ['account_id'], unique=False)
    op.create_table('next_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('action_type', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_next_actions_account_id'), 'next_actions', ['account_id'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source_type', sa.String(length=60), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'url', name='uq_account_source_url')
    )
    op.create_index(op.f('ix_sources_account_id'), 'sources', ['account_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('source_title', sa.String(length=500), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_type', sa.String(length=60), nullable=False),
    sa.Column('supported_claim', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('evidence_level', sa.String(length=40), nullable=False),
    sa.Column('freshness_status', sa.String(length=40), nullable=False),
    sa.Column('claim_type', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'source_id', 'supported_claim', name='uq_evidence_claim')
    )
    op.create_index(op.f('ix_evidence_account_id'), 'evidence', ['account_id'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_account_id'), 'locations', ['account_id'], unique=False)
    op.create_table('opportunities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('fit_score_id', sa.String(length=36), nullable=False),
    sa.Column('classification', sa.String(length=60), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['fit_score_id'], ['fit_scores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_account_id'), 'opportunities', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunities_account_id'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_locations_account_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_evidence_account_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_sources_account_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_next_actions_account_id'), table_name='next_actions')
    op.drop_table('next_actions')
    op.drop_index(op.f('ix_fit_scores_account_id'), table_name='fit_scores')
    op.drop_table('fit_scores')
    op.drop_index(op.f('ix_audit_events_account_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_approvals_account_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_accounts_normalized_name'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_domain'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
